alias k="kubectl "
alias kgp="kubectl get po "
alias kgn="kubectl get node "
alias kgs="kubectl get svc "
alias kgpo="kubectl get po --owide "
alias kn="kubectl config set-context --current --namespace "
alias ka="kubectl apply -f "
alias krep="kubectl replace --force -f "
alias kgd="kubectl get deploy "
alias kr="kubectl run --dry-run=client -oyaml --image "
export do="--dry-run=client -oyaml "