# nodes = [
#   { :host => "cp", :box => "bento/ubuntu-22.04-arm64", :gui => false, :ip => "192.168.80.135", :cpu => 1, :ram => 1024 }, 
#   { :host => "worker1", :box => "bento/ubuntu-22.04-arm64", :gui => false, :ip => "192.168.80.136", :cpu => 1, :ram => 1024 },
#   { :host => "worker2", :box => "bento/ubuntu-22.04-arm64", :gui => false, :ip => "192.168.80.137", :cpu => 1, :ram => 1024 },
# ]
# IP_NW="10.0.0."
# IP_START=10
nodes = [
  { :host => "cp", :box => "bento/ubuntu-22.04-arm64", :gui => false, :ip => "192.168.89.131", :cpu => 2, :ram => 2048 }, 
  { :host => "worker1", :box => "bento/ubuntu-22.04-arm64", :gui => false, :ip => "192.168.89.132", :cpu => 1, :ram => 1024 },
  { :host => "worker2", :box => "bento/ubuntu-22.04-arm64", :gui => false, :ip => "192.168.89.133", :cpu => 1, :ram => 1024 },
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:host] do |config|
      config.vm.box = node[:box]
      # config.vm.network "private_network", type: "dhcp"
      config.vm.network "private_network", ip: node[:ip], :netmask => "255.255.255.0"
      config.vm.hostname = "#{node[:host]}"
      config.vm.provider "vmware_desktop" do |v|
        v.gui = node[:gui]
        v.memory = node[:ram]
        v.cpus = node[:cpu]
      end
      if node[:host] == "cp" then
        config.vm.provision "shell", path: "../scripts/common.sh"
        config.vm.provision "shell", path: "../scripts/control-plane.sh"
      else
        config.vm.provision "shell", path: "../scripts/common.sh"
        config.vm.provision "shell", path: "../scripts/worker.sh"
      end
      
    end
  end
end